### ISSUE TITLE
Issues with address violation 

### ISSUE THREAD

**Issue by kleiberjp** [rakam-io/rakam-ios#2]
Debugging the application with the Address sanitizer enabled, we found an exception that may cause crashes

```
==35191==ERROR: AddressSanitizer: odr-violation (0x0001241ca2a0):
  [1] size=8 'IDENTIFY_EVENT' /Users/kperez/rappi/ios-rappi/apps/Grability/Pods/Rakam-iOS/Rakam/RakamConstants.m:33:17
    #0 0x1377b862e in __asan_register_globals (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x1362e)
    #1 0x1377fff00 in __asan::AsanApplyToGlobals(void (*)(__asan_global*, unsigned long), void const*) (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x5af00)
    #2 0x1377b856e in __asan_register_image_globals (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x1356e)
    #3 0x10e272826 in asan.module_ctor (Grability:x86_64+0x100005826)
    #4 0x1377157b7 in ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) (dyld_sim:x86_64+0x137b7)
    #5 0x1377109a1 in ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) (dyld_sim:x86_64+0xe9a1)
    #6 0x13770f7a5 in ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) (dyld_sim:x86_64+0xd7a5)
    #7 0x13770f845 in ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) (dyld_sim:x86_64+0xd845)
    #8 0x13770408b in dyld::initializeMainExecutable() (dyld_sim:x86_64+0x208b)
    #9 0x1377080fb in dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) (dyld_sim:x86_64+0x60fb)
    #10 0x1377031cc in start_sim (dyld_sim:x86_64+0x11cc)
    #11 0x1452c88cb  (<unknown module>)
    #12 0x1452c6574  (<unknown module>)
    #13 0x1452c1226  (<unknown module>)
    #14 0x1452c1024  (<unknown module>)

  [2]:
    #0 0x1377b862e in __asan_register_globals (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x1362e)
    #1 0x1377fff00 in __asan::AsanApplyToGlobals(void (*)(__asan_global*, unsigned long), void const*) (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x5af00)
    #2 0x1377b856e in __asan_register_image_globals (libclang_rt.asan_iossim_dynamic.dylib:x86_64+0x1356e)
    #3 0x10e272826 in asan.module_ctor (Grability:x86_64+0x100005826)
    #4 0x1377157b7 in ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) (dyld_sim:x86_64+0x137b7)
    #5 0x1377109a1 in ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) (dyld_sim:x86_64+0xe9a1)
    #6 0x13770f7a5 in ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) (dyld_sim:x86_64+0xd7a5)
    #7 0x13770f845 in ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) (dyld_sim:x86_64+0xd845)
    #8 0x13770408b in dyld::initializeMainExecutable() (dyld_sim:x86_64+0x208b)
    #9 0x1377080fb in dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) (dyld_sim:x86_64+0x60fb)
    #10 0x1377031cc in start_sim (dyld_sim:x86_64+0x11cc)
    #11 0x1452c88cb  (<unknown module>)
    #12 0x1452c6574  (<unknown module>)
    #13 0x1452c1226  (<unknown module>)
    #14 0x1452c1024  (<unknown module>)

==35191==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global 'IDENTIFY_EVENT' at /Users/kperez/rappi/ios-rappi/apps/Grability/Pods/Rakam-iOS/Rakam/RakamConstants.m:33:17
==35191==ABORTING
```

**Comment by ilkerc** [comment]
Hi, @kleiberjp looks like you're observing this exception on a simulator, did you had a similar one while testing on a device? I've created a sandbox project with address sanitizer enabled. However, I couldn't reproduce the exception. Can you describe the steps, please?

Also, I personally use the address sanitizer to catch the memory corruptions too. However, since it is disabled on the production build `odr-violation` can't be a reason to crash the app.
